# 端口
server:
  port: 8090
# 服务名称
spring:
  application:
    name: winvaz-boot
  # 多环境
  profiles:
    active: dev
  # 文件上传
  servlet:
    multipart:
      enabled: true # 开启文件上传
      max-file-size: 10MB # 限制文件上传大小为10M

# JWT
jwt:
  tokenHeader: Authorization # JWT存储的请求头
  secret: winvaz-boot-secret # JWT加解密使用的密钥
  expiration: 604800 # JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer ' # JWT负载中拿到开头

redis:
  database: winvaz
  key:
    admin: 'ums:admin'
    resourceList: 'ums:resourceList'
  expire:
    common: 60 * 60 * 24 # 24小时

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /admin/info
      - /admin/logout
      - /minio/upload
